import { LiveEvent, Genre, ReservationTask, IngestionStats, SeatSection } from './types';

export const initialGenres: Genre[] = [
  { id: 1, name_ar: "كأس العالم للرياضات الإلكترونية", name_en: "Esports World Cup (EWC)", slug: "ewc", is_active: true, event_count: 12 },
  { id: 2, name_ar: "الحفلات والموسيقى", name_en: "Concerts & Music", slug: "concerts", is_active: true, event_count: 16 },
  { id: 3, name_ar: "كرة القدم ودوري روشن", name_en: "Football & SPL", slug: "football", is_active: true, event_count: 24 },
  { id: 4, name_ar: "فعاليات عالمية ورياضية", name_en: "Global & Mega Sports", slug: "global", is_active: true, event_count: 14 },
  { id: 5, name_ar: "المطاعم وتجارب فيا رياض", name_en: "Restaurants & Dining", slug: "restaurants", is_active: true, event_count: 8 },
  { id: 6, name_ar: "التجارب وبوليفارد وورلد", name_en: "Experiences & Boulevard", slug: "experiences", is_active: true, event_count: 20 },
  { id: 7, name_ar: "العروض والمسرح", name_en: "Shows & Theater", slug: "shows", is_active: true, event_count: 10 },
  { id: 8, name_ar: "السفر والطيران", name_en: "Travel & Flights", slug: "flights", is_active: true, event_count: 6 },
  { id: 9, name_ar: "الفنادق والمزادات", name_en: "Hotels & Auctions", slug: "hotels", is_active: true, event_count: 5 },
];

export const initialEvents: LiveEvent[] = [
  // --- 0. Exact Live Events from Webook.com/ar (August 2026) ---
  {
    id: 1,
    webook_id: "wbk_ewc_2026_riyadh",
    genre_id: 1,
    genre_slug: "ewc",
    title_ar: "كأس العالم للرياضات الإلكترونية (Esports World Cup 2026)",
    title_en: "Esports World Cup 2026 (EWC) - Boulevard Riyadh City",
    slug: "esports-world-cup-ewc-riyadh-2026",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "بوليفارد رياض سيتي - SEF أرينا، الرياض",
    venue_address: "Boulevard Riyadh City, Hittin, Riyadh",
    city: "الرياض",
    starts_at: "2026-07-06T14:00:00Z",
    ends_at: "2026-08-23T23:00:00Z",
    min_price: 20,
    max_price: 1500,
    image_url: "https://picsum.photos/seed/esports-world-cup-ewc-riyadh-2026/800/600",
    chart_token: "ch_webook_ewc_2026",
    chart_key: "seatcloud_ewc_boulevard",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "الحدث الأضخم تاريخياً في عالم الجيمينج والرياضات الإلكترونية بجوائز تفوق 60 مليون دولار وأكثر من 22 بطولة في بوليفارد رياض سيتي.",
    sections: [
      { id: "sec_ewc_day", name: "تذكرة دخول يومية (Day Pass)", category_name: "General Admission", price: 20, available_seats: 1450, total_seats: 6000, color: "#3b82f6" },
      { id: "sec_ewc_arena", name: "تذكرة الأرينا الرئيسية (Main Arena)", category_name: "Arena Gold", price: 85, available_seats: 320, total_seats: 2500, color: "#10b981" },
      { id: "sec_ewc_vip", name: "باقة اللاعبين وكبار الشخصيات VIP Pass", category_name: "VIP Lounge", price: 650, available_seats: 45, total_seats: 200, color: "#eab308" },
      { id: "sec_ewc_all", name: "الباقة الموسمية الشاملة All-Tournament", category_name: "Ultimate Season Pass", price: 1500, available_seats: 12, total_seats: 80, color: "#ec4899" },
    ]
  },
  {
    id: 2,
    webook_id: "wbk_tamer_ashour_jeddah_2026",
    genre_id: 2,
    genre_slug: "concerts",
    title_ar: "حفلة تامر عاشور - جدة (GEA Benchmark)",
    title_en: "Tamer Ashour Live Concert - Benchmark Jeddah",
    slug: "tamer-ashour-live-jeddah-concert-2026",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "مسرح عبادي الجوهر أرينا - جدة",
    venue_address: "Abadi Al Johar Arena, King Abdulaziz Rd, Jeddah",
    city: "جدة",
    starts_at: "2026-08-27T17:30:00Z",
    ends_at: "2026-08-27T23:30:00Z",
    min_price: 375,
    max_price: 2500,
    image_url: "https://picsum.photos/seed/tamer-ashour-live-jeddah-concert-2026/800/600",
    chart_token: "ch_webook_tamer_ashour_jeddah",
    chart_key: "seatcloud_abadi_arena",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "فعالية 27 أغسطس، فتح الأبواب 8:30، بداية الحفل 9:30 مساءً في جدة برعاية الهيئة العامة للترفيه وتنظيم Benchmark.",
    sections: [
      { id: "sec_ta_bronze", name: "الدرجة الفضية (Silver Grandstand)", category_name: "Silver Tier", price: 375, available_seats: 85, total_seats: 1200, color: "#64748b" },
      { id: "sec_ta_gold", name: "الدرجة الذهبية (Gold Premium)", category_name: "Gold Premium", price: 650, available_seats: 38, total_seats: 800, color: "#eab308" },
      { id: "sec_ta_plat", name: "البلاتينية أمام المسرح مباشرة", category_name: "Platinum Front Stage", price: 1200, available_seats: 14, total_seats: 300, color: "#3b82f6" },
      { id: "sec_ta_vip", name: "المقصورة الملكية كبار الشخصيات VIP", category_name: "VIP Royal Box", price: 2500, available_seats: 4, total_seats: 50, color: "#ec4899" },
    ]
  },
  {
    id: 3,
    webook_id: "wbk_angham_jeddah_2026",
    genre_id: 2,
    genre_slug: "concerts",
    title_ar: "حفلة صوت مصر الفنانة أنغام - جدة",
    title_en: "Angham Live in Concert - Jeddah",
    slug: "angham-live-jeddah-concert-2026",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "مسرح عبادي الجوهر أرينا - جدة",
    venue_address: "Abadi Al Johar Arena, King Abdulaziz Rd, Jeddah",
    city: "جدة",
    starts_at: "2026-08-14T17:30:00Z",
    ends_at: "2026-08-14T23:30:00Z",
    min_price: 375,
    max_price: 2800,
    image_url: "https://picsum.photos/seed/angham-live-jeddah-concert-2026/800/600",
    chart_token: "ch_webook_angham_jeddah",
    chart_key: "seatcloud_abadi_arena",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "فعالية 14 أغسطس، فتح الأبواب: 8:30 مساءً، بداية الحفل: 9:30 مساءً - جدة، المملكة العربية السعودية. ليلة طربية استثنائية مع صوت مصر.",
    sections: [
      { id: "sec_ang_c3", name: "الدرجة الفضية (Silver)", category_name: "Silver", price: 375, available_seats: 42, total_seats: 1200, color: "#64748b" },
      { id: "sec_ang_c2", name: "الدرجة الذهبية (Gold)", category_name: "Gold", price: 750, available_seats: 19, total_seats: 600, color: "#eab308" },
      { id: "sec_ang_vip", name: "الدرجة الماسية VIP Lounge", category_name: "VIP Diamond", price: 1600, available_seats: 8, total_seats: 150, color: "#3b82f6" },
      { id: "sec_ang_royal", name: "المقصورة الملكية Royal Hospitality", category_name: "Royal Hospitality", price: 2800, available_seats: 2, total_seats: 30, color: "#ec4899" },
    ]
  },
  {
    id: 4,
    webook_id: "wbk_le_mans_portimao_2026",
    genre_id: 4,
    genre_slug: "global",
    title_ar: "European Le Mans Series 2026 (سباق لومان الأوروبي)",
    title_en: "European Le Mans Series 2026 - Portimao",
    slug: "european-le-mans-series-2026-portimao",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "حلبة أوتودرومو دو ألغارف - بورتيماو، البرتغال",
    venue_address: "Autodromo Internacional do Algarve, Portimao, Portugal",
    city: "بورتيماو، البرتغال",
    starts_at: "2026-10-09T08:00:00Z",
    ends_at: "2026-10-10T20:00:00Z",
    min_price: 34.61,
    max_price: 450,
    image_url: "https://picsum.photos/seed/european-le-mans-series-2026-portimao/800/600",
    chart_token: "ch_webook_elms_portimao",
    chart_key: "seatcloud_elms",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "فعالية 9 أكتوبر إلى 10 أكتوبر 2026 - بورتيماو، البرتغال. 47 سيارة و6 سباقات لومان الأسطورية مع حجز فوري حصري عبر Webook.",
    sections: [
      { id: "sec_elms_gen", name: "تذكرة دخول عام للسباق (General Entry)", category_name: "General Admission", price: 34.61, available_seats: 1200, total_seats: 5000, color: "#3b82f6" },
      { id: "sec_elms_paddock", name: "تذكرة البادوك ومنطقة الصيانة (Paddock Pass)", category_name: "Paddock Access", price: 145, available_seats: 180, total_seats: 800, color: "#10b981" },
      { id: "sec_elms_vip", name: "لاونج كبار الشخصيات VIP Lounge", category_name: "VIP Hospitality", price: 450, available_seats: 30, total_seats: 120, color: "#eab308" },
    ]
  },
  {
    id: 5,
    webook_id: "wbk_f1_spanish_gp_2026",
    genre_id: 4,
    genre_slug: "global",
    title_ar: "فورمولا 1 تاغ هوير الجائزة الكبرى لإسبانيا 2026",
    title_en: "Formula 1 TAG Heuer Spanish Grand Prix 2026 - Madrid",
    slug: "f1-tag-heuer-spanish-grand-prix-madrid-2026",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "حلبة مدريد الجديدة للفورمولا 1 - مدريد، إسبانيا",
    venue_address: "Madrid F1 Street Circuit, Madrid, Spain",
    city: "مدريد، إسبانيا",
    starts_at: "2026-09-11T09:00:00Z",
    ends_at: "2026-09-13T18:00:00Z",
    min_price: 50,
    max_price: 3200,
    image_url: "https://picsum.photos/seed/f1-tag-heuer-spanish-grand-prix-madrid-2026/800/600",
    chart_token: "ch_webook_f1_madrid_2026",
    chart_key: "seatcloud_f1_madrid",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "بطولة الجائزة الكبرى للفورمولا 1 تاغ هوير في مدريد، إسبانيا. تذاكر رسمية ومباشرة عبر Webook العالمية.",
    sections: [
      { id: "sec_f1_gen", name: "دخول عام للمدرج المفتوح (General Entry)", category_name: "Pelousse General", price: 50, available_seats: 2400, total_seats: 10000, color: "#3b82f6" },
      { id: "sec_f1_grand", name: "مدرج المنعطف الأول (Grandstand Turn 1)", category_name: "Turn 1 Grandstand", price: 420, available_seats: 210, total_seats: 2000, color: "#10b981" },
      { id: "sec_f1_paddock", name: "نادي بaddock كلوب كبار الشخصيات F1 Paddock", category_name: "F1 Paddock Club", price: 3200, available_seats: 15, total_seats: 80, color: "#ec4899" },
    ]
  },
  {
    id: 6,
    webook_id: "wbk_ac_milan_san_siro_2026",
    genre_id: 3,
    genre_slug: "football",
    title_ar: "مباريات موسم إي سي ميلان (AC Milan) - سان سيرو",
    title_en: "AC Milan Season Matches 2026/2027 - San Siro Stadium",
    slug: "ac-milan-season-tickets-san-siro-2026",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "ملعب سان سيرو (San Siro Stadium) - ميلانو، إيطاليا",
    venue_address: "Piazzale Angelo Moratti, Milan, Italy",
    city: "ميلانو، إيطاليا",
    starts_at: "2026-09-01T18:45:00Z",
    ends_at: "2027-05-30T22:00:00Z",
    min_price: 50,
    max_price: 1800,
    image_url: "https://picsum.photos/seed/ac-milan-season-tickets-san-siro-2026/800/600",
    chart_token: "ch_webook_ac_milan_san_siro",
    chart_key: "seatcloud_san_siro",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "تذاكر مباريات نادي إي سي ميلان في الدوري الإيطالي ودوري أبطال أوروبا على ملعب سان سيرو التاريخي بميلانو حصرياً على Webook.",
    sections: [
      { id: "sec_mil_curva", name: "مدرج كورفا سود (Curva Sud)", category_name: "Curva Sud Fan Zone", price: 50, available_seats: 650, total_seats: 12000, color: "#64748b" },
      { id: "sec_mil_lat", name: "المدرج الجانبي الشرقي (Primo Anello)", category_name: "Lateral Tier 1", price: 160, available_seats: 120, total_seats: 4000, color: "#3b82f6" },
      { id: "sec_mil_vip", name: "صالة ميلان للضيافة VIP Hospitality Lounge", category_name: "VIP Lounge", price: 1800, available_seats: 18, total_seats: 90, color: "#eab308" },
    ]
  },
  {
    id: 7,
    webook_id: "wbk_myazu_via_riyadh",
    genre_id: 5,
    genre_slug: "restaurants",
    title_ar: "مطعم ميازو - الرياض (فيا رياض)",
    title_en: "Myazu Restaurant - Via Riyadh",
    slug: "myazu-restaurant-via-riyadh-reservations",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "فيا رياض (Via Riyadh) - حي الهدا، الرياض",
    venue_address: "Via Riyadh Luxury Complex, Al Hada, Riyadh",
    city: "الرياض",
    starts_at: "2026-08-14T12:00:00Z",
    ends_at: "2026-08-14T23:59:00Z",
    min_price: 50,
    max_price: 800,
    image_url: "https://picsum.photos/seed/myazu-restaurant-via-riyadh-reservations/800/600",
    chart_token: "ch_webook_myazu_via",
    chart_key: "seatcloud_myazu",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "مطعم ميازو الراقي في فيا رياض يقدم فن الطهي الياباني المعاصر، حجز فوري ومضمون مع باقات الطاولات الحصرية.",
    sections: [
      { id: "sec_my_dep", name: "تأكيد حجز طاولة لشخصين", category_name: "Table Deposit (2 Guests)", price: 50, available_seats: 14, total_seats: 40, color: "#3b82f6" },
      { id: "sec_my_chef", name: "طاولة تجربة الشيف كاونتر (Chef's Counter)", category_name: "Chef Tasting Experience", price: 350, available_seats: 6, total_seats: 16, color: "#eab308" },
      { id: "sec_my_vip", name: "غرفة كبار الشخصيات الخاصة Private VIP Dining", category_name: "Private VIP Room", price: 800, available_seats: 2, total_seats: 5, color: "#ec4899" },
    ]
  },
  {
    id: 8,
    webook_id: "wbk_ferdi_via_riyadh",
    genre_id: 5,
    genre_slug: "restaurants",
    title_ar: "مطعم فيردي - الرياض (فيا رياض)",
    title_en: "Ferdi Restaurant - Via Riyadh",
    slug: "ferdi-restaurant-via-riyadh-table-booking",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "فيا رياض (Via Riyadh) - حي الهدا، الرياض",
    venue_address: "Via Riyadh Luxury Complex, Al Hada, Riyadh",
    city: "الرياض",
    starts_at: "2026-08-14T12:00:00Z",
    ends_at: "2026-08-14T23:59:00Z",
    min_price: 50,
    max_price: 650,
    image_url: "https://picsum.photos/seed/ferdi-restaurant-via-riyadh-table-booking/800/600",
    chart_token: "ch_webook_ferdi_via",
    chart_key: "seatcloud_ferdi",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "المطعم الباريسي الشهير فيردي في فيا رياض مع أطباق البرغر المميزة والمقبلات الفرنسية، حجز فوري فائق السرعة عبر Webook.",
    sections: [
      { id: "sec_fr_tbl", name: "حجز طاولة داخلية لشخصين", category_name: "Indoor Table for 2", price: 50, available_seats: 18, total_seats: 50, color: "#3b82f6" },
      { id: "sec_fr_ter", name: "طاولة التراس الخارجي المطل", category_name: "Outdoor Terrace Table", price: 120, available_seats: 8, total_seats: 25, color: "#10b981" },
      { id: "sec_fr_vip", name: "باقة العشاء الفاخر VIP Set Menu", category_name: "VIP Dining Experience", price: 650, available_seats: 4, total_seats: 10, color: "#ec4899" },
    ]
  },
  {
    id: 9,
    webook_id: "wbk_vega_cigar_lounge_via",
    genre_id: 5,
    genre_slug: "restaurants",
    title_ar: "فيغا سيجار لاونج (فيا رياض)",
    title_en: "Vega Cigar Lounge - Via Riyadh",
    slug: "vega-cigar-lounge-via-riyadh-access",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "فيا رياض (Via Riyadh) - حي الهدا، الرياض",
    venue_address: "Via Riyadh Luxury Complex, Al Hada, Riyadh",
    city: "الرياض",
    starts_at: "2026-08-14T16:00:00Z",
    ends_at: "2026-08-15T02:00:00Z",
    min_price: 200,
    max_price: 1200,
    image_url: "https://picsum.photos/seed/vega-cigar-lounge-via-riyadh-access/800/600",
    chart_token: "ch_webook_vega_via",
    chart_key: "seatcloud_vega",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "لاونج فيغا الفاخر في فيا رياض لعشاق الأجواء الراقية والمشروبات الفاخرة، حجز فوري للمقاعد واللاونج الخاص.",
    sections: [
      { id: "sec_vg_entry", name: "حجز جلسة لاونج للأفراد (Lounge Access)", category_name: "Lounge Seat Pass", price: 200, available_seats: 12, total_seats: 35, color: "#eab308" },
      { id: "sec_vg_booth", name: "جلسة خاصة لكبار الشخصيات VIP Booth", category_name: "VIP Private Booth", price: 1200, available_seats: 3, total_seats: 8, color: "#ec4899" },
    ]
  },
  {
    id: 101,
    webook_id: "wbk_six_kings_slam_2026",
    genre_id: 4,
    genre_slug: "mega-sports",
    title_ar: "بطولة الملوك الستة للتنس (6 Kings Slam) - موسم الرياض",
    title_en: "Six Kings Slam Tennis Championship - Riyadh Season",
    slug: "six-kings-slam-tennis-riyadh-season-2026",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "ذا فينيو أرينا (The Venue) - بوليفارد سيتي",
    venue_address: "The Venue Arena, Boulevard Riyadh City, Riyadh",
    city: "الرياض",
    starts_at: "2026-10-14T17:00:00Z",
    ends_at: "2026-10-18T23:00:00Z",
    min_price: 150,
    max_price: 3500,
    image_url: "https://picsum.photos/seed/six-kings-slam-tennis-riyadh-season-2026/800/600",
    chart_token: "ch_webook_sixkings_venue_2026",
    chart_key: "seatcloud_sixkings_venue",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "أقوى بطولة تنس استعراضية في العالم تجمع نخبة أساطير التنس: نوفاك ديوكوفيتش، رافاييل نادال، كارلوس ألكاراز، ويانيك سينر في أرينا ذا فينيو بموسم الرياض.",
    sections: [
      { id: "sec_upper", name: "المدرجات العلوية - Upper Deck", category_name: "Cat 3 Grandstand", price: 150, available_seats: 380, total_seats: 1500, color: "#64748b" },
      { id: "sec_lower", name: "الدرجة الأولى - Lower Bowl", category_name: "Cat 1 Premium", price: 450, available_seats: 110, total_seats: 800, color: "#3b82f6" },
      { id: "sec_court", name: "بجانب الملعب - Courtside VIP", category_name: "Courtside Gold", price: 1800, available_seats: 24, total_seats: 120, color: "#eab308" },
      { id: "sec_royal", name: "المقصورة الملكية Royal Box", category_name: "Royal Hospitality Box", price: 3500, available_seats: 6, total_seats: 30, color: "#ec4899" },
    ]
  },
  {
    id: 102,
    webook_id: "wbk_blvd_world_season_2026",
    genre_id: 1,
    genre_slug: "riyadh-season",
    title_ar: "تذاكر دخول بوليفارد وورلد (Boulevard World) - موسم الرياض",
    title_en: "Boulevard World Entry & Zones Tickets - Riyadh Season",
    slug: "boulevard-world-riyadh-season-zones-2026",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "بوليفارد وورلد - حطين، الرياض",
    venue_address: "Prince Turki Ibn Abdulaziz Al Awwal Rd, Hittin, Riyadh",
    city: "الرياض",
    starts_at: "2026-10-01T16:00:00Z",
    ends_at: "2027-03-30T01:00:00Z",
    min_price: 30,
    max_price: 350,
    image_url: "https://picsum.photos/seed/boulevard-world-riyadh-season-zones-2026/800/600",
    chart_token: "ch_webook_blvd_world_all",
    chart_key: "seatcloud_blvd_world",
    seats_provider: "general_admission",
    synced_at: new Date().toISOString(),
    description: "استكشف 14 دولة وثقافة عالمية في مكان واحد: إيطاليا، فرنسا، المكسيك، اليونان، بريطانيا، اليابان، ومصر مع أكبر بحيرة اصطناعية وتلفريك في العالم.",
    sections: [
      { id: "sec_entry_gen", name: "تذكرة دخول عام (أيام الأسبوع)", category_name: "Weekday Entry", price: 30, available_seats: 2500, total_seats: 8000, color: "#3b82f6" },
      { id: "sec_entry_wknd", name: "تذكرة دخول نهاية الأسبوع", category_name: "Weekend Entry", price: 50, available_seats: 1200, total_seats: 10000, color: "#10b981" },
      { id: "sec_gold_pass", name: "الباقة الذهبية (دخول + ألعاب ومراكب)", category_name: "Gold All-Access Pass", price: 210, available_seats: 350, total_seats: 1200, color: "#eab308" },
      { id: "sec_vip_fast", name: "تذكرة المسار السريع VIP Fast Track", category_name: "VIP Fast Pass", price: 350, available_seats: 75, total_seats: 300, color: "#8b5cf6" },
    ]
  },
  {
    id: 103,
    webook_id: "wbk_wonder_garden_rs",
    genre_id: 1,
    genre_slug: "riyadh-season",
    title_ar: "تذاكر وندر جاردن (Wonder Garden) - مدينة الملاهي الساحرة",
    title_en: "Wonder Garden Amusement Park - Riyadh Season",
    slug: "wonder-garden-riyadh-season-tickets",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "وندر جاردن - حي الملك فهد، الرياض",
    venue_address: "King Fahd District, Northern Ring Rd, Riyadh",
    city: "الرياض",
    starts_at: "2026-11-01T16:00:00Z",
    ends_at: "2027-02-28T00:00:00Z",
    min_price: 35,
    max_price: 290,
    image_url: "https://picsum.photos/seed/wonder-garden-riyadh-season-tickets/800/600",
    chart_token: "ch_webook_wonder_garden",
    chart_key: "seatcloud_wonder_garden",
    seats_provider: "general_admission",
    synced_at: new Date().toISOString(),
    description: "مدينة ملاهي خيالية متكاملة تضم 3 مناطق رئيسية: حديقة الفراشات، الحديقة السحرية، وشجرة الحياة مع أكثر من 65 لعبة وتجربة حية.",
    sections: [
      { id: "sec_wg_gen", name: "تذكرة دخول عام", category_name: "General Admission", price: 35, available_seats: 1800, total_seats: 6000, color: "#3b82f6" },
      { id: "sec_wg_rides", name: "باقة الدخول الشامل للألعاب", category_name: "All-Rides Pass", price: 180, available_seats: 420, total_seats: 1500, color: "#10b981" },
      { id: "sec_wg_fast", name: "تذكرة VIP مسار سريع", category_name: "VIP Fast Pass", price: 290, available_seats: 60, total_seats: 250, color: "#eab308" },
    ]
  },
  {
    id: 104,
    webook_id: "wbk_suwaidi_park_rs",
    genre_id: 1,
    genre_slug: "riyadh-season",
    title_ar: "مهرجانات حديقة السويدي الثقافية (Al Suwaidi Park)",
    title_en: "Al Suwaidi Park Cultural Festivals - Riyadh Season",
    slug: "al-suwaidi-park-cultural-festivals",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "حديقة السويدي - جنوب الرياض",
    venue_address: "Al Suwaidi, Southern Riyadh",
    city: "الرياض",
    starts_at: "2026-10-15T16:00:00Z",
    ends_at: "2027-01-15T23:00:00Z",
    min_price: 15,
    max_price: 120,
    image_url: "https://picsum.photos/seed/al-suwaidi-park-cultural-festivals/800/600",
    chart_token: "ch_webook_suwaidi",
    chart_key: "seatcloud_suwaidi",
    seats_provider: "general_admission",
    synced_at: new Date().toISOString(),
    description: "تستضيف حديقة السويدي 9 ثقافات عالمية أسبوعية تستعرض الفنون الشعبية والمأكولات والأزياء التقليدية من الفلبين، الهند، إندونيسيا، مصر، وغيرها.",
    sections: [
      { id: "sec_sw_entry", name: "تذكرة دخول الفعاليات", category_name: "Standard Entry", price: 15, available_seats: 3200, total_seats: 8000, color: "#10b981" },
      { id: "sec_sw_family", name: "باقة العائلة (4 أفراد)", category_name: "Family Bundle", price: 50, available_seats: 500, total_seats: 1200, color: "#3b82f6" },
    ]
  },
  {
    id: 105,
    webook_id: "wbk_souq_al_awaleen",
    genre_id: 1,
    genre_slug: "riyadh-season",
    title_ar: "سوق الأولين (Souq Al Awaleen) - التراث والأسواق النجدية",
    title_en: "Souq Al Awaleen - Najdi Heritage Market",
    slug: "souq-al-awaleen-riyadh-season",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "سوق الأولين - حي العقيق، الرياض",
    venue_address: "Al Aqiq District, Riyadh",
    city: "الرياض",
    starts_at: "2026-11-10T16:00:00Z",
    ends_at: "2027-02-15T23:30:00Z",
    min_price: 20,
    max_price: 95,
    image_url: "https://picsum.photos/seed/souq-al-awaleen-riyadh-season/800/600",
    chart_token: "ch_webook_awaleen",
    chart_key: "seatcloud_awaleen",
    seats_provider: "general_admission",
    synced_at: new Date().toISOString(),
    description: "رحلة تسوق تراثية إلى نجد القديمة في حقبة السبعينيات مع أكبر دكاكين للحرف اليدوية والمأكولات الشعبية وتجربة سوق الحراج الحية.",
    sections: [
      { id: "sec_aw_entry", name: "تذكرة دخول السوق", category_name: "Market Access", price: 20, available_seats: 2100, total_seats: 5000, color: "#eab308" },
      { id: "sec_aw_pass", name: "باقة الدخول + تجربة الحراج والضيافة", category_name: "Heritage Hospitality Pass", price: 95, available_seats: 280, total_seats: 800, color: "#10b981" },
    ]
  },

  // --- 2. Saudi Pro League (دوري روشن السعودي) ---
  {
    id: 106,
    webook_id: "wbk_derby_riyadh_hilal_nassr",
    genre_id: 2,
    genre_slug: "sports",
    title_ar: "ديربي الرياض: الهلال ضد النصر - دوري روشن السعودي",
    title_en: "Riyadh Derby: Al Hilal vs Al Nassr - Saudi Pro League",
    slug: "al-hilal-vs-al-nassr-riyadh-derby-spl-2026",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "المملكة أرينا (Kingdom Arena) - الرياض",
    venue_address: "King Fahd Branch Rd, Al Malqa, Riyadh",
    city: "الرياض",
    starts_at: "2026-09-18T18:00:00Z",
    ends_at: "2026-09-18T20:30:00Z",
    min_price: 35,
    max_price: 2500,
    image_url: "https://picsum.photos/seed/al-hilal-vs-al-nassr-riyadh-derby-spl-2026/800/600",
    chart_token: "ch_webook_kingdom_arena_derby",
    chart_key: "seatcloud_ka_derby",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "قمة القمم الكروية في ديربي العاصمة المشتعل بين الهلال والنصر بكامل نجومهم العالميين على ملعب المملكة أرينا المغلق بتغطية Webook الرسمية.",
    sections: [
      { id: "sec_cat3", name: "الدرجة الثالثة (خلف المرمى - رابطة المشجعين)", category_name: "Cat 3 Behind Goal", price: 35, available_seats: 420, total_seats: 4000, color: "#64748b" },
      { id: "sec_cat2", name: "الدرجة الثانية (الأركان والزوايا)", category_name: "Cat 2 Corners", price: 95, available_seats: 180, total_seats: 3000, color: "#3b82f6" },
      { id: "sec_cat1", name: "الدرجة الأولى (الواجهة الرئيسية)", category_name: "Cat 1 Main Stand", price: 350, available_seats: 55, total_seats: 1600, color: "#10b981" },
      { id: "sec_vip_lounge", name: "باقة كبار الشخصيات VIP Lounge", category_name: "VIP Executive Lounge", price: 2500, available_seats: 8, total_seats: 90, color: "#ec4899" },
    ]
  },
  {
    id: 107,
    webook_id: "wbk_derby_jeddah_ittihad_ahli",
    genre_id: 2,
    genre_slug: "sports",
    title_ar: "ديربي البحر والجوهرة: الاتحاد ضد الأهلي - دوري روشن",
    title_en: "Jeddah Derby: Al Ittihad vs Al Ahli - Saudi Pro League",
    slug: "al-ittihad-vs-al-ahli-jeddah-derby-spl-2026",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "مدينة الملك عبدالله الرياضية (الجوهرة المشعة) - جدة",
    venue_address: "King Abdullah Sports City Stadium, Jeddah",
    city: "جدة",
    starts_at: "2026-10-02T18:00:00Z",
    ends_at: "2026-10-02T20:30:00Z",
    min_price: 30,
    max_price: 2200,
    image_url: "https://picsum.photos/seed/al-ittihad-vs-al-ahli-jeddah-derby-spl-2026/800/600",
    chart_token: "ch_webook_jawhara_derby",
    chart_key: "seatcloud_jawhara",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "كلاسيكو وديربي جدة التاريخي على مدرجات الجوهرة المشعة بحضور أكثر من 60 ألف مشجع وبنزيمة ومحرز وفيرمينو وكانتي.",
    sections: [
      { id: "sec_j_upper", name: "الدرجة الموحدة (المدرج العلوي)", category_name: "Unified Upper Tier", price: 30, available_seats: 1200, total_seats: 25000, color: "#64748b" },
      { id: "sec_j_lower", name: "الواجهة السفلية الممتازة", category_name: "Lower Main Stand", price: 120, available_seats: 310, total_seats: 15000, color: "#3b82f6" },
      { id: "sec_j_silver", name: "المنصة الفضية Silver Hospitality", category_name: "Silver Hospitality", price: 900, available_seats: 35, total_seats: 500, color: "#eab308" },
      { id: "sec_j_gold", name: "المنصة الذهبية Gold VIP", category_name: "Gold VIP Box", price: 2200, available_seats: 10, total_seats: 120, color: "#ec4899" },
    ]
  },
  {
    id: 108,
    webook_id: "wbk_nassr_vs_damac",
    genre_id: 2,
    genre_slug: "sports",
    title_ar: "النصر ضد ضمك - دوري روشن السعودي (الأول بارك)",
    title_en: "Al Nassr vs Damac - Saudi Pro League (Al Awwal Park)",
    slug: "spl-alnassr-vs-damac-533869",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "استاد الأول بارك (Al Awwal Park) - الرياض",
    venue_address: "King Saud University Stadium, Riyadh",
    city: "الرياض",
    starts_at: "2026-09-22T18:00:00Z",
    ends_at: "2026-09-22T20:00:00Z",
    min_price: 30,
    max_price: 1800,
    image_url: "https://picsum.photos/seed/spl-alnassr-vs-damac-533869/800/600",
    chart_token: "ch_webook_awwal_damac",
    chart_key: "seatcloud_awwal_park",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "مباراة النصر بقيادة كريستيانو رونالدو وساديو ماني ضد فريق ضمك في الجولة القادمة على أرضية ملعب الأول بارك.",
    sections: [
      { id: "sec_ap_cat3", name: "الدرجة الثالثة (شمال / جنوب)", category_name: "Cat 3 Behind Goal", price: 30, available_seats: 580, total_seats: 5000, color: "#64748b" },
      { id: "sec_ap_cat1", name: "الدرجة الأولى (واجهة شرقية)", category_name: "Cat 1 East Stand", price: 150, available_seats: 90, total_seats: 2500, color: "#3b82f6" },
      { id: "sec_ap_lounge", name: "لاونج الأول بارك كبار الشخصيات", category_name: "Al Awwal Lounge VIP", price: 1800, available_seats: 12, total_seats: 80, color: "#eab308" },
    ]
  },
  {
    id: 109,
    webook_id: "wbk_spl_alqadsiah_vs_alkhaleej",
    genre_id: 2,
    genre_slug: "sports",
    title_ar: "القادسية ضد الخليج - دوري روشن السعودي (استاد الدمام)",
    title_en: "Al Qadsiah vs Al Khaleej - Saudi Pro League",
    slug: "spl-alqadsiah-vs-alkhaleej-906720",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "استاد الأمير محمد بن فهد - الدمام",
    venue_address: "Prince Mohamed bin Fahd Stadium, Dammam",
    city: "الدمام",
    starts_at: "2026-09-12T18:00:00Z",
    ends_at: "2026-09-12T20:00:00Z",
    min_price: 25,
    max_price: 350,
    image_url: "https://picsum.photos/seed/spl-alqadsiah-vs-alkhaleej-906720/800/600",
    chart_token: "ch_webook_spl_qadsiah_906720",
    chart_key: "seatcloud_qadsiah",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "مواجهة قوية ضمن منافسات دوري روشن السعودي بين فرسان القادسية وبحارة الخليج على استاد الأمير محمد بن فهد.",
    sections: [
      { id: "sec_gen", name: "المدرجات العامة (عائلات وأفراد)", category_name: "General Admission", price: 25, available_seats: 850, total_seats: 5000, color: "#3b82f6" },
      { id: "sec_prem", name: "الدرجة الأولى الممتازة", category_name: "Cat 1 Premium", price: 85, available_seats: 160, total_seats: 1200, color: "#10b981" },
      { id: "sec_vip", name: "المقصورة الرئيسية VIP", category_name: "VIP Lounge", price: 350, available_seats: 15, total_seats: 80, color: "#eab308" },
    ]
  },
  {
    id: 110,
    webook_id: "wbk_spl_raed_vs_orobah",
    genre_id: 2,
    genre_slug: "sports",
    title_ar: "الرائد ضد العروبة - دوري روشن السعودي (بريدة)",
    title_en: "Al Raed vs Al Orobah - Saudi Pro League",
    slug: "spl-raed-vs-orobah-tickets-293804",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "مدينة الملك عبدالله الرياضية - بريدة",
    venue_address: "King Abdullah Sports City Stadium, Buraidah",
    city: "بريدة",
    starts_at: "2026-09-15T18:30:00Z",
    ends_at: "2026-09-15T20:30:00Z",
    min_price: 20,
    max_price: 200,
    image_url: "https://picsum.photos/seed/spl-raed-vs-orobah-tickets-293804/800/600",
    chart_token: "ch_webook_raed_orobah",
    chart_key: "seatcloud_buraidah",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "تذاكر مباراة نادي الرائد ضد نادي العروبة ضمن الجولة الرسمية لدوري روشن السعودي للمحترفين بمدينة الملك عبدالله الرياضية.",
    sections: [
      { id: "sec_gen", name: "المدرجات العامة (عائلات وأفراد)", category_name: "General Admission", price: 20, available_seats: 950, total_seats: 4000, color: "#3b82f6" },
      { id: "sec_vip", name: "المنصة الرئيسية VIP", category_name: "VIP Stand", price: 200, available_seats: 25, total_seats: 100, color: "#eab308" },
    ]
  },
  {
    id: 111,
    webook_id: "wbk_spl_ett_vs_itt",
    genre_id: 2,
    genre_slug: "sports",
    title_ar: "الاتفاق ضد الاتحاد - دوري روشن السعودي (استاد الاتفاق)",
    title_en: "Al Ettifaq vs Al Ittihad - Saudi Pro League",
    slug: "spl-ett-vs-itt-792500",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "استاد نادي الاتفاق (EGO Stadium) - الدمام",
    venue_address: "Al Ettifaq Club Stadium, Dammam",
    city: "الدمام",
    starts_at: "2026-10-08T18:00:00Z",
    ends_at: "2026-10-08T20:00:00Z",
    min_price: 35,
    max_price: 650,
    image_url: "https://picsum.photos/seed/spl-ett-vs-itt-792500/800/600",
    chart_token: "ch_webook_ett_itt",
    chart_key: "seatcloud_ettifaq",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "مواجهة كبرى في الشرقية تجمع الاتفاق مع العميد نادي الاتحاد في لقاء حاسم على استاد نادي الاتفاق الجديد بالدمام.",
    sections: [
      { id: "sec_ett_gen", name: "المدرج الموحد (جمهور الاتفاق / الاتحاد)", category_name: "Standard Tier", price: 35, available_seats: 600, total_seats: 7000, color: "#3b82f6" },
      { id: "sec_ett_prem", name: "الدرجة الأولى الممتازة", category_name: "Cat 1 Premium", price: 120, available_seats: 80, total_seats: 1200, color: "#10b981" },
      { id: "sec_ett_vip", name: "المقصورة الذهبية VIP", category_name: "Gold VIP", price: 650, available_seats: 12, total_seats: 60, color: "#eab308" },
    ]
  },
  {
    id: 112,
    webook_id: "wbk_okhdood_vs_shabab",
    genre_id: 2,
    genre_slug: "sports",
    title_ar: "الأخدود ضد الشباب - دوري روشن السعودي (نجران)",
    title_en: "Al Okhdood vs Al Shabab - Saudi Pro League",
    slug: "al-okhdood-vs-al-shabab",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "مدينة الأمير هذلول بن عبدالعزيز الرياضية - نجران",
    venue_address: "Prince Hathloul Sports City Stadium, Najran",
    city: "نجران",
    starts_at: "2026-09-28T17:30:00Z",
    ends_at: "2026-09-28T19:30:00Z",
    min_price: 20,
    max_price: 250,
    image_url: "https://picsum.photos/seed/al-okhdood-vs-al-shabab/800/600",
    chart_token: "ch_webook_okhdood_shabab",
    chart_key: "seatcloud_najran",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "مباراة نادي الأخدود مع ضيفه نادي الشباب في دوري روشن السعودي للمحترفين بمدينة الأمير هذلول بنجران.",
    sections: [
      { id: "sec_gen", name: "الدرجة الموحدة", category_name: "General Admission", price: 20, available_seats: 750, total_seats: 5000, color: "#3b82f6" },
      { id: "sec_vip", name: "المنصة الرئيسية VIP", category_name: "VIP Lounge", price: 250, available_seats: 18, total_seats: 70, color: "#eab308" },
    ]
  },
  {
    id: 113,
    webook_id: "wbk_qadsiah_season_ticket",
    genre_id: 2,
    genre_slug: "sports",
    title_ar: "التذاكر الموسمية لنادي القادسية (Al Qadsiah Season Pass)",
    title_en: "Al Qadsiah FC Official Seasonal Pass - 2026/2027",
    slug: "al-qadsiah--season--tickets-702295",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "استاد الأمير محمد بن فهد - الدمام والخبر",
    venue_address: "Prince Mohamed bin Fahd Stadium, Eastern Province",
    city: "الدمام",
    starts_at: "2026-08-25T00:00:00Z",
    ends_at: "2027-05-30T23:59:59Z",
    min_price: 250,
    max_price: 4500,
    image_url: "https://picsum.photos/seed/al-qadsiah--season--tickets-702295/800/600",
    chart_token: "ch_webook_qadsiah_season",
    chart_key: "seatcloud_qadsiah_season",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "احجز مقعدك الدائم طوال الموسم لجميع مباريات القادسية على أرضه في دوري روشن وكأس خادم الحرمين الشريفين مع مزايا حصرية للأعضاء.",
    sections: [
      { id: "sec_season_gen", name: "المقعد الموسمي العام", category_name: "Seasonal General", price: 250, available_seats: 450, total_seats: 2000, color: "#3b82f6" },
      { id: "sec_season_prem", name: "المقعد الموسمي الممتاز الواجهة", category_name: "Seasonal Premium", price: 750, available_seats: 120, total_seats: 500, color: "#10b981" },
      { id: "sec_season_vip", name: "العضوية الماسية VIP Box الموسمي", category_name: "Seasonal Diamond VIP", price: 4500, available_seats: 14, total_seats: 40, color: "#ec4899" },
    ]
  },

  // --- 3. Concerts, Music & Festivals ---
  {
    id: 114,
    webook_id: "wbk_assala_jalsat_rs",
    genre_id: 3,
    genre_slug: "concerts",
    title_ar: "جلسات موسم الرياض: ليلة أصالة نصري (Assala Nasri Live)",
    title_en: "Jalsat Riyadh Season: Assala Live Concert",
    slug: "assala-jalsat-riyadh-season-747983",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "مسرح محمد عبده أرينا - بوليفارد سيتي",
    venue_address: "Boulevard Riyadh City, Hittin, Riyadh",
    city: "الرياض",
    starts_at: "2026-10-09T20:30:00Z",
    ends_at: "2026-10-10T01:30:00Z",
    min_price: 250,
    max_price: 3200,
    image_url: "https://picsum.photos/seed/assala-jalsat-riyadh-season-747983/800/600",
    chart_token: "ch_webook_assala_rs",
    chart_key: "seatcloud_abdo_arena",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "ليلة طربية ساحرة مع أيقونة الشرق أصالة نصري تقدم فيها باقة من أروع أغانيها الخليجية والعربية برفقة الفرقة الموسيقية الكبرى.",
    sections: [
      { id: "sec_bronze", name: "البرونزية - المدرج العلوي", category_name: "Bronze Balcony", price: 250, available_seats: 95, total_seats: 1200, color: "#cd7f32" },
      { id: "sec_silver", name: "الفضية - الوسط", category_name: "Silver Tier", price: 650, available_seats: 38, total_seats: 800, color: "#94a3b8" },
      { id: "sec_gold", name: "الذهبية - المقاعد الأمامية", category_name: "Gold Stalls", price: 1450, available_seats: 14, total_seats: 400, color: "#eab308" },
      { id: "sec_diamond", name: "الماسية VIP - الصفوف الأولى", category_name: "Diamond Front Row", price: 3200, available_seats: 6, total_seats: 60, color: "#8b5cf6" },
    ]
  },
  {
    id: 115,
    webook_id: "wbk_mohammed_abdo_tarab_26",
    genre_id: 3,
    genre_slug: "concerts",
    title_ar: "ليلة فنان العرب محمد عبده - مسرح محمد عبده أرينا",
    title_en: "Mohammed Abdo Live Concert - Mohammed Abdo Arena",
    slug: "mohammed-abdo-riyadh-gala-concert-2026",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "مسرح محمد عبده أرينا - بوليفارد سيتي",
    venue_address: "Boulevard Riyadh City, Hittin, Riyadh",
    city: "الرياض",
    starts_at: "2026-09-25T20:30:00Z",
    ends_at: "2026-09-26T01:30:00Z",
    min_price: 300,
    max_price: 3800,
    image_url: "https://picsum.photos/seed/mohammed-abdo-riyadh-gala-concert-2026/800/600",
    chart_token: "ch_webook_abdo_arena_live",
    chart_key: "seatcloud_abdo_arena",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "حفل طربي استثنائي مع فنان العرب محمد عبده برفقة أوركسترا موسيقية عالمية بقيادة المايسترو وليد فايد.",
    sections: [
      { id: "sec_bronze", name: "البرونزية - المدرج العلوي", category_name: "Bronze Balcony", price: 300, available_seats: 85, total_seats: 1200, color: "#cd7f32" },
      { id: "sec_silver", name: "الفضية - الوسط", category_name: "Silver Tier", price: 750, available_seats: 42, total_seats: 800, color: "#94a3b8" },
      { id: "sec_gold", name: "الذهبية - المقاعد الأمامية", category_name: "Gold Stalls", price: 1650, available_seats: 18, total_seats: 400, color: "#eab308" },
      { id: "sec_diamond", name: "الماسية - الصفوف الأولى VIP", category_name: "Diamond Front Row", price: 3800, available_seats: 4, total_seats: 60, color: "#8b5cf6" },
    ]
  },
  {
    id: 116,
    webook_id: "wbk_mdlbeast_soundstorm_26",
    genre_id: 3,
    genre_slug: "concerts",
    title_ar: "مهرجان ساوند ستورم مدل بيست 2026 (MDLBEAST Soundstorm)",
    title_en: "Soundstorm MDLBEAST Festival 2026 - Banban",
    slug: "mdlbeast-soundstorm-2026-riyadh-banban",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "أراضي مهرجان بنبان - شمال الرياض",
    venue_address: "Banban Festival Grounds, Riyadh",
    city: "الرياض",
    starts_at: "2026-12-10T16:00:00Z",
    ends_at: "2026-12-13T03:00:00Z",
    min_price: 199,
    max_price: 4900,
    image_url: "https://picsum.photos/seed/mdlbeast-soundstorm-2026-riyadh-banban/800/600",
    chart_token: "ch_webook_mdlbeast_soundstorm",
    chart_key: "seatcloud_mdlbeast",
    seats_provider: "general_admission",
    synced_at: new Date().toISOString(),
    description: "أضخم مهرجان موسيقي في الشرق الأوسط بمشاركة أكثر من 200 دي جي وفنان عالمي وعربي عبر 8 مسارح عملاقة في بنبان.",
    sections: [
      { id: "sec_storm_ga", name: "تذكرة ستورم اليومية (GA)", category_name: "General Admission Storm", price: 199, available_seats: 1400, total_seats: 15000, color: "#3b82f6" },
      { id: "sec_storm_3day", name: "باقة 3 أيام كاملة (Storm Pass)", category_name: "3-Day Festival Pass", price: 499, available_seats: 800, total_seats: 8000, color: "#10b981" },
      { id: "sec_vib", name: "باقة الشخصيات الهامة (VIB Premium)", category_name: "VIB Exclusive Lounge", price: 1999, available_seats: 120, total_seats: 1500, color: "#eab308" },
      { id: "sec_vib_box", name: "باقة شرفات VIB Box المرتفعة", category_name: "VIB High Table Box", price: 4900, available_seats: 12, total_seats: 100, color: "#ec4899" },
    ]
  },
  {
    id: 117,
    webook_id: "wbk_beast_house_jax",
    genre_id: 3,
    genre_slug: "concerts",
    title_ar: "حفلات بيست هاوس جاكس الدرعية (Beast House - JAX)",
    title_en: "MDLBEAST Beast House - JAX Diriyah",
    slug: "mdlbeast-beast-house-ec",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "بيست هاوس - حي جاكس للفنون، الدرعية",
    venue_address: "JAX Art District, Diriyah, Riyadh",
    city: "الرياض",
    starts_at: "2026-09-05T21:00:00Z",
    ends_at: "2026-09-06T03:00:00Z",
    min_price: 150,
    max_price: 750,
    image_url: "https://picsum.photos/seed/mdlbeast-beast-house-ec/800/600",
    chart_token: "ch_webook_beast_house",
    chart_key: "seatcloud_beast_house",
    seats_provider: "general_admission",
    synced_at: new Date().toISOString(),
    description: "أمسيات موسيقية إلكترونية حصرية في أول نادي موسيقي خاص للمبدعين وعشاق الموسيقى الإيقاعية في حي جاكس الدرعية.",
    sections: [
      { id: "sec_bh_entry", name: "تذكرة دخول عام (Club Access)", category_name: "General Admission", price: 150, available_seats: 140, total_seats: 400, color: "#3b82f6" },
      { id: "sec_bh_vip", name: "طاولة VIP خاصة (4 أفراد)", category_name: "VIP Table", price: 750, available_seats: 8, total_seats: 25, color: "#eab308" },
    ]
  },
  {
    id: 118,
    webook_id: "wbk_yemeni_orchestra_moc",
    genre_id: 3,
    genre_slug: "concerts",
    title_ar: "سيمفونية التراث اليمني - الأوركسترا اليمنية (وزارة الثقافة)",
    title_en: "The Yemeni Heritage Orchestra - King Fahad Cultural Centre",
    slug: "the-yemeni-orchestra-moc",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "مركز الملك فهد الثقافي - الرياض",
    venue_address: "King Fahad Cultural Centre, Riyadh",
    city: "الرياض",
    starts_at: "2026-10-22T20:00:00Z",
    ends_at: "2026-10-22T23:30:00Z",
    min_price: 120,
    max_price: 950,
    image_url: "https://picsum.photos/seed/the-yemeni-orchestra-moc/800/600",
    chart_token: "ch_webook_yemeni_moc",
    chart_key: "seatcloud_kfcc",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "أمسية أوركسترالية فريدة تستعرض روائع التراث والموسيقى اليمنية بمشاركة كبار العازفين والمنشدين برعاية وزارة الثقافة.",
    sections: [
      { id: "sec_balcony", name: "الشرفة العلوية", category_name: "Balcony", price: 120, available_seats: 120, total_seats: 600, color: "#64748b" },
      { id: "sec_stalls", name: "القاعة الرئيسية", category_name: "Main Stalls", price: 350, available_seats: 80, total_seats: 500, color: "#3b82f6" },
      { id: "sec_vip", name: "الصفوف الأولى VIP", category_name: "VIP Orchestra", price: 950, available_seats: 12, total_seats: 60, color: "#ec4899" },
    ]
  },
  {
    id: 119,
    webook_id: "wbk_final_fantasy_symphony",
    genre_id: 3,
    genre_slug: "concerts",
    title_ar: "حفل فاينل فانتسي السيمفوني (Final Fantasy XIV in Symphony)",
    title_en: "Final Fantasy XIV in Symphony - Abu Bakr Salem Stage",
    slug: "final-fantasy-xiv-in-symphony",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "مسرح أبو بكر سالم - بوليفارد سيتي",
    venue_address: "Boulevard Riyadh City, Riyadh",
    city: "الرياض",
    starts_at: "2026-11-18T20:00:00Z",
    ends_at: "2026-11-18T23:00:00Z",
    min_price: 150,
    max_price: 850,
    image_url: "https://picsum.photos/seed/final-fantasy-xiv-in-symphony/800/600",
    chart_token: "ch_webook_ff_symphony",
    chart_key: "seatcloud_ffxiv",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "أوركسترا حية ضخمة تعزف المقطوعات الأيقونية للعبة Final Fantasy بمصاحبة شاشات عرض عملاقة ومشاهد ملحمية.",
    sections: [
      { id: "sec_upper", name: "المدرج العلوي", category_name: "Upper Tier", price: 150, available_seats: 190, total_seats: 800, color: "#64748b" },
      { id: "sec_orch", name: "القاعة الموسيقية الرئيسية", category_name: "Orchestra Tier", price: 380, available_seats: 65, total_seats: 400, color: "#3b82f6" },
      { id: "sec_vip", name: "المقاعد الذهبية الأمامية", category_name: "Gold VIP Stalls", price: 850, available_seats: 18, total_seats: 80, color: "#eab308" },
    ]
  },

  // --- 4. World Championships & WWE (البطولات العالمية) ---
  {
    id: 120,
    webook_id: "wbk_wwe_crown_jewel_riyadh_26",
    genre_id: 4,
    genre_slug: "mega-sports",
    title_ar: "عرض WWE كراون جول السنوي (WWE Crown Jewel) - الرياض",
    title_en: "WWE Crown Jewel 2026 - Riyadh Superdome Arena",
    slug: "wwe-crown-jewel-superdome-riyadh-2026",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "محمد عبده أرينا / بوليفارد هول - الرياض",
    venue_address: "Boulevard Arena & Superdome, Riyadh",
    city: "الرياض",
    starts_at: "2026-11-06T18:30:00Z",
    ends_at: "2026-11-06T23:30:00Z",
    min_price: 130,
    max_price: 3200,
    image_url: "https://picsum.photos/seed/wwe-crown-jewel-superdome-riyadh-2026/800/600",
    chart_token: "ch_webook_wwe_crownjewel_26",
    chart_key: "seatcloud_wwe_superdome",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "أضخم عروض المصارعة الحرة العالمية من WWE بمشاركة كودي رودز، رومان رينز، سيث رولينز، وجون سينا على أحزمة العالم.",
    sections: [
      { id: "sec_upper", name: "المدرجات العلوية - Upper Deck", category_name: "Tier 3", price: 130, available_seats: 290, total_seats: 2500, color: "#64748b" },
      { id: "sec_lower", name: "المدرجات السفلية - Lower Bowl", category_name: "Tier 2", price: 380, available_seats: 64, total_seats: 1800, color: "#3b82f6" },
      { id: "sec_ringside", name: "بجانب الحلبة - Ringside VIP", category_name: "Ringside Tier 1", price: 3200, available_seats: 5, total_seats: 120, color: "#f43f5e" },
    ]
  },
  {
    id: 121,
    webook_id: "wbk_pfl_championships_riyadh",
    genre_id: 4,
    genre_slug: "mega-sports",
    title_ar: "نهائيات بطولة الفنون القتالية المختلطة (PFL World Championships)",
    title_en: "PFL World Championships Finals - The Venue Arena",
    slug: "pfl-championships-239842",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "ذا فينيو أرينا (The Venue) - بوليفارد سيتي",
    venue_address: "The Venue Arena, Boulevard Riyadh City",
    city: "الرياض",
    starts_at: "2026-11-27T17:00:00Z",
    ends_at: "2026-11-27T23:30:00Z",
    min_price: 120,
    max_price: 2400,
    image_url: "https://picsum.photos/seed/pfl-championships-239842/800/600",
    chart_token: "ch_webook_pfl_finals",
    chart_key: "seatcloud_pfl",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "ليلة النزالات العالمية الكبرى في رياضة MMA لتتويج أبطال العالم لـ 6 فئات أوزان مختلفة بجوائز تتجاوز ملايين الدولارات.",
    sections: [
      { id: "sec_pfl_ga", name: "المدرج العام", category_name: "Tier 2 Seating", price: 120, available_seats: 340, total_seats: 2000, color: "#3b82f6" },
      { id: "sec_pfl_cage", name: "بجانب القفص - Cage Side VIP", category_name: "VIP Cage Side", price: 1400, available_seats: 16, total_seats: 100, color: "#eab308" },
      { id: "sec_pfl_box", name: "المقصورة الفاخرة VIP Box", category_name: "VIP Hospitality", price: 2400, available_seats: 4, total_seats: 25, color: "#ec4899" },
    ]
  },
  {
    id: 122,
    webook_id: "wbk_f1_saudi_gp_jeddah_2027",
    genre_id: 4,
    genre_slug: "mega-sports",
    title_ar: "سباق جائزة السعودية الكبرى للفورمولا 1 (Formula 1 STC Saudi GP)",
    title_en: "Formula 1 STC Saudi Arabian Grand Prix - Jeddah Corniche",
    slug: "f1-saudi-arabian-grand-prix-jeddah-corniche-2027",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "حلبة كورنيش جدة - جدة",
    venue_address: "Jeddah Corniche Circuit, Northern Corniche, Jeddah",
    city: "جدة",
    starts_at: "2027-03-19T17:00:00Z",
    ends_at: "2027-03-21T21:00:00Z",
    min_price: 250,
    max_price: 6500,
    image_url: "https://picsum.photos/seed/f1-saudi-arabian-grand-prix-jeddah-corniche-2027/800/600",
    chart_token: "ch_webook_f1_jeddah_2027",
    chart_key: "seatcloud_f1_jeddah",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "أسرع حلبة شوارع في العالم تشهد أقوى سباقات السرعة والإثارة لسيارات الفورمولا 1 بمشاركة أبطال العالم وحفلات غنائية مصاحبة.",
    sections: [
      { id: "sec_ga", name: "الدخول العام (General Admission)", category_name: "General Admission", price: 250, available_seats: 800, total_seats: 5000, color: "#3b82f6" },
      { id: "sec_main_grandstand", name: "المدرج الرئيسي - خط البداية والنهاية", category_name: "Main Grandstand", price: 950, available_seats: 160, total_seats: 2500, color: "#10b981" },
      { id: "sec_paddock", name: "نادي البادوك الفاخر (Paddock Club VIP)", category_name: "VIP Paddock Club", price: 6500, available_seats: 12, total_seats: 80, color: "#ec4899" },
    ]
  },
  {
    id: 123,
    webook_id: "wbk_riyadh_racing_horse",
    genre_id: 4,
    genre_slug: "mega-sports",
    title_ar: "أمسيات سباقات الخيل - ميدان الملك عبدالعزيز بالجنادرية (JCSA)",
    title_en: "Riyadh Horse Racing Season - King Abdulaziz Racecourse",
    slug: "riyadh-racing-season-rsace-night-16",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "ميدان الملك عبدالعزيز للفروسية - الجنادرية، الرياض",
    venue_address: "King Abdulaziz Racecourse, Janadriyah, Riyadh",
    city: "الرياض",
    starts_at: "2026-09-18T15:00:00Z",
    ends_at: "2026-09-18T21:00:00Z",
    min_price: 25,
    max_price: 850,
    image_url: "https://picsum.photos/seed/riyadh-racing-season-rsace-night-16/800/600",
    chart_token: "ch_webook_jcsa_race",
    chart_key: "seatcloud_jcsa",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "أقوى سباقات الخيل والفروسية السعودية تحت إشراف نادي سباقات الخيل (JCSA) في أجواء عائلية وتراثية فاخرة.",
    sections: [
      { id: "sec_jcsa_gen", name: "تذكرة الدخول العام للمدرجات", category_name: "Grandstand Entry", price: 25, available_seats: 1200, total_seats: 5000, color: "#3b82f6" },
      { id: "sec_jcsa_terrace", name: "شرفة الضيافة الممتازة", category_name: "Terrace Dining", price: 220, available_seats: 90, total_seats: 300, color: "#10b981" },
      { id: "sec_jcsa_vip", name: "المقصورة الملكية للفروسية VIP", category_name: "Royal Enclosure", price: 850, available_seats: 15, total_seats: 60, color: "#eab308" },
    ]
  },
  {
    id: 124,
    webook_id: "wbk_saudi_cup_2027",
    genre_id: 4,
    genre_slug: "mega-sports",
    title_ar: "أمسية كأس السعودية العالمي للخيل 2027 (The Saudi Cup)",
    title_en: "The Saudi Cup World Horse Racing Championship 2027",
    slug: "saudi-cup-season",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "ميدان الملك عبدالعزيز للفروسية - الجنادرية",
    venue_address: "Janadriyah, Riyadh",
    city: "الرياض",
    starts_at: "2027-02-26T14:00:00Z",
    ends_at: "2027-02-27T22:00:00Z",
    min_price: 90,
    max_price: 5200,
    image_url: "https://picsum.photos/seed/saudi-cup-season/800/600",
    chart_token: "ch_webook_saudicup",
    chart_key: "seatcloud_saudicup",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "أغلى سباق خيل في العالم بجوائز تبلغ 37.5 مليون دولار مع عروض أزياء تراثية وأرقى تجارب الضيافة النجدية.",
    sections: [
      { id: "sec_sc_ga", name: "الدخول العام وقرية السباق", category_name: "Village Access", price: 90, available_seats: 1500, total_seats: 6000, color: "#3b82f6" },
      { id: "sec_sc_prem", name: "مدرج خط النهاية الفاخر", category_name: "Finish Line Grandstand", price: 450, available_seats: 210, total_seats: 1200, color: "#10b981" },
      { id: "sec_sc_vip", name: "جناح الضيافة الملكية VIP Hospitality", category_name: "Royal Hospitality", price: 5200, available_seats: 8, total_seats: 50, color: "#ec4899" },
    ]
  },

  // --- 5. Theater & Comedy Shows (المسرح والكوميديا) ---
  {
    id: 125,
    webook_id: "wbk_alf_taita_we_taita",
    genre_id: 5,
    genre_slug: "theater",
    title_ar: "مسرحية ألف تيتة وتيتة - أكرم حسني وميرنا جميل (مسرح محمد العلي)",
    title_en: "Alf Taita We Taita Play - Akram Hosny & Mirna Gamil",
    slug: "alf-taita-we-taita-rs-24",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "مسرح محمد العلي - بوليفارد سيتي",
    venue_address: "Boulevard Riyadh City, Riyadh",
    city: "الرياض",
    starts_at: "2026-10-18T21:00:00Z",
    ends_at: "2026-10-23T23:45:00Z",
    min_price: 90,
    max_price: 900,
    image_url: "https://picsum.photos/seed/alf-taita-we-taita-rs-24/800/600",
    chart_token: "ch_webook_taita_play",
    chart_key: "seatcloud_mohammed_ali",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "مسرحية كوميدية غنائية استعراضية من بطولة النجم أكرم حسني وميرنا جميل وبيومي فؤاد تدور في إطار فانتازي ساخر.",
    sections: [
      { id: "sec_c", name: "الدرجة الثالثة C", category_name: "Standard Cat C", price: 90, available_seats: 120, total_seats: 400, color: "#64748b" },
      { id: "sec_b", name: "الدرجة الثانية B", category_name: "Premium Cat B", price: 240, available_seats: 60, total_seats: 280, color: "#3b82f6" },
      { id: "sec_a", name: "الدرجة الأولى VIP A", category_name: "VIP Front", price: 900, available_seats: 16, total_seats: 70, color: "#10b981" },
    ]
  },
  {
    id: 126,
    webook_id: "wbk_bakr_shaddi_theater_26",
    genre_id: 5,
    genre_slug: "theater",
    title_ar: "مسرحية السندباد - كريم عبدالعزيز ونيللي كريم (مسرح بكر الشدي)",
    title_en: "The Sinbad Play - Karim Abdelaziz & Nelly Karim",
    slug: "the-king-and-the-people-bakr-shaddi-play-2026",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "مسرح بكر الشدي - بوليفارد سيتي",
    venue_address: "Boulevard Riyadh City, Theater Zone, Riyadh",
    city: "الرياض",
    starts_at: "2026-09-10T21:00:00Z",
    ends_at: "2026-09-15T23:45:00Z",
    min_price: 110,
    max_price: 1100,
    image_url: "https://picsum.photos/seed/the-king-and-the-people-bakr-shaddi-play-2026/800/600",
    chart_token: "ch_webook_bakr_shaddi_helmy",
    chart_key: "seatcloud_bakr_shaddi",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "عمل مسرحي كوميدي مغامرات ضخم للنجم كريم عبدالعزيز ونيللي كريم ومصطفى خاطر في رحلة ساحرة عبر الزمن.",
    sections: [
      { id: "sec_c", name: "الدرجة الثالثة C", category_name: "Standard Cat C", price: 110, available_seats: 95, total_seats: 350, color: "#64748b" },
      { id: "sec_b", name: "الدرجة الثانية B", category_name: "Premium Cat B", price: 280, available_seats: 52, total_seats: 250, color: "#3b82f6" },
      { id: "sec_a", name: "الدرجة الأولى VIP A", category_name: "VIP Front", price: 1100, available_seats: 14, total_seats: 80, color: "#10b981" },
    ]
  },
  {
    id: 127,
    webook_id: "wbk_one_mic_comedy",
    genre_id: 5,
    genre_slug: "theater",
    title_ar: "عروض وان مايك ستاند أب كوميدي (One Mic Comedy Shows)",
    title_en: "One Mic Comedy Live Stand-up Shows - Riyadh",
    slug: "one-mic-comedy-shows-tickets-873299",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "مسرح ون مايك - حي النرجس، الرياض",
    venue_address: "An Narjis District, Riyadh",
    city: "الرياض",
    starts_at: "2026-09-08T20:30:00Z",
    ends_at: "2026-09-08T22:30:00Z",
    min_price: 60,
    max_price: 250,
    image_url: "https://picsum.photos/seed/one-mic-comedy-shows-tickets-873299/800/600",
    chart_token: "ch_webook_onemic",
    chart_key: "seatcloud_onemic",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "أمسيات ضحك وكوميديا ارتجالية أسبوعية تجمع ألمع نجوم الستاند أب كوميدي في الرياض.",
    sections: [
      { id: "sec_om_gen", name: "دخول عام (مقاعد المسرح)", category_name: "General Admission", price: 60, available_seats: 110, total_seats: 220, color: "#3b82f6" },
      { id: "sec_om_front", name: "طاولات الصفوف الأولى", category_name: "Front Row VIP", price: 250, available_seats: 14, total_seats: 40, color: "#eab308" },
    ]
  },
  {
    id: 128,
    webook_id: "wbk_mina_nader_show",
    genre_id: 5,
    genre_slug: "theater",
    title_ar: "عرض الستاند أب كوميدي: مينا نادر (Mina Nader Show)",
    title_en: "Mina Nader Comedy Special Live in Riyadh",
    slug: "mina-nader-show-620418",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "مسرح الكوميديا كلوب - الرياض",
    venue_address: "Riyadh Comedy Club Stage, Riyadh",
    city: "الرياض",
    starts_at: "2026-09-19T21:00:00Z",
    ends_at: "2026-09-19T22:45:00Z",
    min_price: 70,
    max_price: 220,
    image_url: "https://picsum.photos/seed/mina-nader-show-620418/800/600",
    chart_token: "ch_webook_mina_nader",
    chart_key: "seatcloud_mina_nader",
    seats_provider: "seatcloud",
    synced_at: new Date().toISOString(),
    description: "العرض الكوميدي الخاص للفنان والكوميديان مينا نادر في ليلة مليئة بالمواقف الساخرة والضحك المتواصل.",
    sections: [
      { id: "sec_mn_gen", name: "تذكرة دخول عام", category_name: "General Tier", price: 70, available_seats: 90, total_seats: 200, color: "#3b82f6" },
      { id: "sec_mn_vip", name: "مقاعد VIP الأمامية", category_name: "VIP Tier", price: 220, available_seats: 12, total_seats: 35, color: "#eab308" },
    ]
  },

  // --- 6. Experiences & Tours (التجارب والفعاليات) ---
  {
    id: 129,
    webook_id: "wbk_awwal_park_tour",
    genre_id: 6,
    genre_slug: "experiences",
    title_ar: "جولة وتجربة استاد الأول بارك الحصرية (Al Awwal Park Stadium Tour)",
    title_en: "Al Awwal Park VIP Stadium Experience & Tour",
    slug: "al-awwal-tour-stadium-tickets-843728",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "استاد الأول بارك - جامعة الملك سعود، الرياض",
    venue_address: "King Saud University, Riyadh",
    city: "الرياض",
    starts_at: "2026-08-20T10:00:00Z",
    ends_at: "2026-12-30T22:00:00Z",
    min_price: 45,
    max_price: 190,
    image_url: "https://picsum.photos/seed/al-awwal-tour-stadium-tickets-843728/800/600",
    chart_token: "ch_webook_awwal_tour",
    chart_key: "seatcloud_awwal_tour",
    seats_provider: "general_admission",
    synced_at: new Date().toISOString(),
    description: "اكتشف كواليس معقل نادي النصر! جولة داخل غرف ملابس اللاعبين، النفق المؤدي لأرضية الملعب، ومتحف الكؤوس التذكاري.",
    sections: [
      { id: "sec_tour_std", name: "جولة الاستاد العامة", category_name: "Standard Stadium Tour", price: 45, available_seats: 400, total_seats: 1000, color: "#3b82f6" },
      { id: "sec_tour_vip", name: "الجولة الذهبية VIP + التقاط صور في غرفة رونالدو", category_name: "VIP Golden Tour", price: 190, available_seats: 45, total_seats: 150, color: "#eab308" },
    ]
  },
  {
    id: 130,
    webook_id: "wbk_comic_con_arabia_26",
    genre_id: 6,
    genre_slug: "experiences",
    title_ar: "كوميك كون أرابيا 2026 (Comic Con Arabia) - واجهة المعارض",
    title_en: "Comic Con Arabia 2026 - Riyadh Exhibition Front",
    slug: "comic-con-arabia-riyadh-expo-2026",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "مركز واجهة الرياض للمعارض والمؤتمرات",
    venue_address: "Airport Rd, Riyadh Exhibition Center",
    city: "الرياض",
    starts_at: "2026-11-20T14:00:00Z",
    ends_at: "2026-11-23T22:00:00Z",
    min_price: 85,
    max_price: 650,
    image_url: "https://picsum.photos/seed/comic-con-arabia-riyadh-expo-2026/800/600",
    chart_token: "ch_webook_comiccon_2026",
    chart_key: "seatcloud_comiccon",
    seats_provider: "general_admission",
    synced_at: new Date().toISOString(),
    description: "ملتقى عشاق الأنمي والألعاب والقصص المصورة مع حضور نجوم هوليوود ومسابقات الكوسبلاي الكبرى وجلسات التوقيع.",
    sections: [
      { id: "sec_cc_daily", name: "تذكرة يوم واحد", category_name: "1-Day Pass", price: 85, available_seats: 1100, total_seats: 6000, color: "#3b82f6" },
      { id: "sec_cc_weekend", name: "باقة نهاية الأسبوع (3 أيام)", category_name: "Weekend Pass", price: 195, available_seats: 450, total_seats: 2500, color: "#10b981" },
      { id: "sec_cc_vip", name: "باقة VIP الذهبية + لقاء المشاهير", category_name: "VIP Celebrity Meet Pass", price: 650, available_seats: 30, total_seats: 150, color: "#eab308" },
    ]
  },
  {
    id: 131,
    webook_id: "wbk_fit_expo_riyadh",
    genre_id: 6,
    genre_slug: "experiences",
    title_ar: "معرض فيت إكسبو الدولي للياقة البدنية والرياضة (Fit Expo Riyadh)",
    title_en: "Fit Expo Riyadh - International Fitness & Health Exhibition",
    slug: "fit-expo-tickets-948503",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "مركز واجهة الرياض للمعارض - الرياض",
    venue_address: "Riyadh Front Exhibition Center, Riyadh",
    city: "الرياض",
    starts_at: "2026-10-29T10:00:00Z",
    ends_at: "2026-10-31T22:00:00Z",
    min_price: 40,
    max_price: 320,
    image_url: "https://picsum.photos/seed/fit-expo-tickets-948503/800/600",
    chart_token: "ch_webook_fit_expo",
    chart_key: "seatcloud_fitexpo",
    seats_provider: "general_admission",
    synced_at: new Date().toISOString(),
    description: "أكبر معرض رياضي في المنطقة يستعرض أحدث أجهزة اللياقة والمكملات الغذائية مع ورش تدريب حية وتحديات كروس فيت بحضور أبطال مستر أولمبيا.",
    sections: [
      { id: "sec_fe_entry", name: "تذكرة دخول المعرض", category_name: "Standard Expo Pass", price: 40, available_seats: 1600, total_seats: 5000, color: "#3b82f6" },
      { id: "sec_fe_vip", name: "تذكرة شاملة ورش العمل ولقاء الأبطال VIP", category_name: "VIP Athlete Pass", price: 320, available_seats: 80, total_seats: 300, color: "#eab308" },
    ]
  },

  // --- 7. Culture & Ministry of Culture Exhibitions (المعارض والثقافة) ---
  {
    id: 132,
    webook_id: "wbk_chinese_contemporary_art",
    genre_id: 7,
    genre_slug: "conferences",
    title_ar: "معرض الفن الصيني المعاصر وورش الخط والزودياك (وزارة الثقافة)",
    title_en: "Chinese Contemporary Art Exhibition - Ministry of Culture",
    slug: "chinese-contemporary-art-exhibition",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "حي جاكس للفنون - الدرعية، الرياض",
    venue_address: "JAX Arts District, Diriyah, Riyadh",
    city: "الرياض",
    starts_at: "2026-09-01T16:00:00Z",
    ends_at: "2026-11-30T23:00:00Z",
    min_price: 25,
    max_price: 150,
    image_url: "https://picsum.photos/seed/chinese-contemporary-art-exhibition/800/600",
    chart_token: "ch_webook_moc_chinese_art",
    chart_key: "seatcloud_chinese_art",
    seats_provider: "general_admission",
    synced_at: new Date().toISOString(),
    description: "معرض ثقافي استثنائي تنظمه وزارة الثقافة يضم لوحات ومنحوتات نادرة لفنانين صينيين مع ورش عمل لتعليم فن الخط والزودياك وحفل الشاي التقليدي.",
    sections: [
      { id: "sec_art_entry", name: "تذكرة دخول المعرض", category_name: "Exhibition Entry", price: 25, available_seats: 850, total_seats: 2500, color: "#3b82f6" },
      { id: "sec_art_workshop", name: "تذكرة المعرض + ورشة الخط والشاي الصيني", category_name: "Workshop Bundle", price: 150, available_seats: 35, total_seats: 80, color: "#10b981" },
    ]
  },
  {
    id: 133,
    webook_id: "wbk_amplify_forum_25",
    genre_id: 7,
    genre_slug: "conferences",
    title_ar: "ملتقى أمبليفاي لصناع المحتوى والإعلام الرقمي (Amplify Forum)",
    title_en: "Amplify Digital Media & Content Creators Forum",
    slug: "amplify-forum-2025-tickets-928457",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "مركز الملك عبدالله المالي (KAFD) - الرياض",
    venue_address: "KAFD Conference Center, Al Aqiq, Riyadh",
    city: "الرياض",
    starts_at: "2026-10-11T09:00:00Z",
    ends_at: "2026-10-12T18:00:00Z",
    min_price: 150,
    max_price: 1200,
    image_url: "https://picsum.photos/seed/amplify-forum-2025-tickets-928457/800/600",
    chart_token: "ch_webook_amplify_kafd",
    chart_key: "seatcloud_amplify",
    seats_provider: "general_admission",
    synced_at: new Date().toISOString(),
    description: "ملتقى دولي يجمع رواد صناعة المحتوى والإعلام الترفيهي ومنصات البودكاست مع جلسات حوارية وجلسات تشبيك مهني.",
    sections: [
      { id: "sec_amp_std", name: "تذكرة حضور الجلسات والمعرض", category_name: "Delegate Pass", price: 150, available_seats: 320, total_seats: 1000, color: "#3b82f6" },
      { id: "sec_amp_vip", name: "باقة VIP شاملة ورش العمل ومأدبة الغداء", category_name: "Executive VIP Pass", price: 1200, available_seats: 40, total_seats: 120, color: "#eab308" },
    ]
  },
  {
    id: 134,
    webook_id: "wbk_kids_culture_moc",
    genre_id: 7,
    genre_slug: "conferences",
    title_ar: "مهرجان ثقافة الطفل والإبداع (Kids Culture MOC)",
    title_en: "Kids Culture & Creativity Festival - Ministry of Culture",
    slug: "kids-culture-moc",
    status: "AVAILABLE",
    hydration_status: "READY",
    venue_name: "قصر الثقافة - حي السفارات، الرياض",
    venue_address: "Diplomatic Quarter, Riyadh",
    city: "الرياض",
    starts_at: "2026-09-04T15:00:00Z",
    ends_at: "2026-09-06T21:00:00Z",
    min_price: 20,
    max_price: 80,
    image_url: "https://picsum.photos/seed/kids-culture-moc/800/600",
    chart_token: "ch_webook_kids_culture",
    chart_key: "seatcloud_kidsculture",
    seats_provider: "general_admission",
    synced_at: new Date().toISOString(),
    description: "فعاليات تفاعلية وورش مسرح ورسم وقراءة قصص تستهدف تنمية مواهب الأطفال في بيئة ثقافية محفزة وممتعة.",
    sections: [
      { id: "sec_kc_child", name: "تذكرة طفل (شاملة الورش)", category_name: "Child Pass", price: 20, available_seats: 450, total_seats: 1000, color: "#10b981" },
      { id: "sec_kc_family", name: "تذكرة عائلية شاملة (طفلين ومرافقين)", category_name: "Family All-Inclusive", price: 80, available_seats: 110, total_seats: 300, color: "#3b82f6" },
    ]
  }
];

export const initialTasks: ReservationTask[] = [
  {
    id: 8042,
    user_id: 914029411,
    account_id: "account_1",
    event_slug: "six-kings-slam-tennis-riyadh-season-2026",
    event_title: "بطولة الملوك الستة للتنس (6 Kings Slam) - موسم الرياض",
    category: "Courtside Gold",
    timeslot_id: "slot_20261014_1700",
    zone: "Courtside VIP Row 2",
    seat_count: 2,
    status: "SUCCESS",
    worker_id: "wrk_sa_riyadh_01",
    reservation_id: "res_9182301",
    hold_token: "wbk_hld_8a92bc71904df1e39a",
    hold_expires_at: new Date(Date.now() + 1000 * 60 * 15).toISOString(),
    retry_count: 0,
    sniper_mode: true,
    created_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    logs: [
      { timestamp: new Date(Date.now() - 1000 * 60 * 10).toISOString(), state: "QUEUED", message: "Task initialized for 6 Kings Slam Tennis (Sniper Mode Active)" },
      { timestamp: new Date(Date.now() - 1000 * 60 * 9).toISOString(), state: "SEARCHING", message: "Probing seat availability for category: Courtside Gold" },
      { timestamp: new Date(Date.now() - 1000 * 60 * 8).toISOString(), state: "HOLDING", message: "Acquired atomic lock on Courtside VIP Row 2 (Seats: C12, C13)" },
      { timestamp: new Date(Date.now() - 1000 * 60 * 8).toISOString(), state: "SUCCESS", message: "Hold token wbk_hld_8a92bc71904df1e39a verified on Webook Cloud. Ready for checkout." },
    ]
  },
  {
    id: 8043,
    user_id: 832049102,
    account_id: "account_2",
    event_slug: "al-hilal-vs-al-nassr-riyadh-derby-spl-2026",
    event_title: "ديربي الرياض: الهلال ضد النصر - دوري روشن",
    category: "Cat 1 Main Stand",
    timeslot_id: "slot_20260918_1800",
    zone: "Main Stand East",
    seat_count: 4,
    status: "RUNNING",
    worker_id: "wrk_sa_riyadh_02",
    retry_count: 1,
    sniper_mode: true,
    created_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 1).toISOString(),
    logs: [
      { timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(), state: "QUEUED", message: "Targeting high concurrency event (Riyadh Derby - Kingdom Arena)" },
      { timestamp: new Date(Date.now() - 1000 * 60 * 3).toISOString(), state: "SEARCHING", message: "Polling seat map delta via SeatCloud WebSocket proxy" },
      { timestamp: new Date(Date.now() - 1000 * 60 * 1).toISOString(), state: "RUNNING", message: "Detected 4 contiguous seats in Section E1. Dispatching reservation payload..." }
    ]
  },
  {
    id: 114,
    user_id: 710294821,
    account_id: "account_1",
    event_slug: "assala-jalsat-riyadh-season-747983",
    event_title: "جلسات موسم الرياض: ليلة أصالة نصري",
    category: "Gold Stalls",
    timeslot_id: "slot_20261009_2030",
    zone: "Front Stalls Row 3",
    seat_count: 2,
    status: "HOLDING",
    worker_id: "wrk_sa_central_01",
    reservation_id: "res_9182399",
    hold_token: "wbk_hld_9831fba8201de39811",
    hold_expires_at: new Date(Date.now() + 1000 * 60 * 12).toISOString(),
    retry_count: 0,
    sniper_mode: false,
    created_at: new Date(Date.now() - 1000 * 60 * 6).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
    logs: [
      { timestamp: new Date(Date.now() - 1000 * 60 * 6).toISOString(), state: "QUEUED", message: "Task received for Assala Concert" },
      { timestamp: new Date(Date.now() - 1000 * 60 * 4).toISOString(), state: "SEARCHING", message: "Locating seats in Gold Stalls tier" },
      { timestamp: new Date(Date.now() - 1000 * 60 * 2).toISOString(), state: "HOLDING", message: "Reserved seats Row 3 (Seats 14, 15). Hold token issued." }
    ]
  },
  {
    id: 8045,
    user_id: 649201948,
    account_id: "account_2",
    event_slug: "mdlbeast-soundstorm-2026-riyadh-banban",
    event_title: "مهرجان ساوند ستورم مدل بيست 2026",
    category: "VIB Premium",
    timeslot_id: "slot_20261210_1600",
    zone: "VIB Zone",
    seat_count: 2,
    status: "SUCCESS",
    worker_id: "wrk_sa_riyadh_01",
    reservation_id: "res_8492012",
    hold_token: "wbk_hld_771920dfa209b119",
    hold_expires_at: new Date(Date.now() + 1000 * 60 * 14).toISOString(),
    retry_count: 0,
    sniper_mode: true,
    created_at: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    logs: [
      { timestamp: new Date(Date.now() - 1000 * 60 * 20).toISOString(), state: "QUEUED", message: "MDLBEAST Soundstorm VIB Task queued" },
      { timestamp: new Date(Date.now() - 1000 * 60 * 19).toISOString(), state: "SEARCHING", message: "Locking VIB pass" },
      { timestamp: new Date(Date.now() - 1000 * 60 * 18).toISOString(), state: "SUCCESS", message: "VIB tokens locked successfully" }
    ]
  }
];

// In-Memory Database Store for Dynamic Operations
class DatabaseStore {
  public genres: Genre[] = [...initialGenres];
  public events: LiveEvent[] = [...initialEvents];
  public tasks: ReservationTask[] = [...initialTasks];
  public lastSyncTime: string = new Date().toISOString();
  public workerStatus = {
    active: true,
    activeWorkers: 12,
    lastSync: new Date().toISOString(),
    status: "HEALTHY",
  };

  public addTask(taskData: Partial<ReservationTask>): ReservationTask {
    return this.createTask(taskData);
  }

  public getStats(): IngestionStats {
    const totalEvents = this.events.length;
    const readyEvents = this.events.filter((e) => e.hydration_status === "READY").length;
    const discoveredEvents = this.events.filter((e) => e.hydration_status === "DISCOVERED").length;
    const failedEvents = this.events.filter((e) => e.hydration_status === "FAILED").length;
    const categorized = this.events.filter((e) => !!e.genre_slug).length;
    const uncategorized = totalEvents - categorized;

    return {
      total_events: totalEvents,
      ready_events: readyEvents,
      discovered_events: discoveredEvents,
      failed_events: failedEvents,
      categorized: categorized,
      uncategorized: uncategorized,
      hydrated: readyEvents,
      "403_failed": 0,
      duplicate_skipped: 14,
    };
  }

  public getEvents(genreSlug?: string, searchQuery?: string, status?: string): LiveEvent[] {
    return this.events.filter((e) => {
      if (genreSlug && genreSlug !== "all" && e.genre_slug !== genreSlug) {
        return false;
      }
      if (status && status !== "all" && e.status !== status) {
        return false;
      }
      if (searchQuery && searchQuery.trim() !== "") {
        const q = searchQuery.toLowerCase().trim();
        const matchTitleAr = e.title_ar.toLowerCase().includes(q);
        const matchTitleEn = e.title_en.toLowerCase().includes(q);
        const matchVenue = e.venue_name.toLowerCase().includes(q);
        const matchCity = e.city ? e.city.toLowerCase().includes(q) : false;
        const matchSlug = e.slug.toLowerCase().includes(q);
        if (!matchTitleAr && !matchTitleEn && !matchVenue && !matchCity && !matchSlug) {
          return false;
        }
      }
      return true;
    });
  }

  public getEventBySlug(slug: string): LiveEvent | undefined {
    return this.events.find((e) => e.slug === slug || e.webook_id === slug);
  }

  public getEventById(id: number): LiveEvent | undefined {
    return this.events.find((e) => e.id === id);
  }

  public createTask(taskData: Partial<ReservationTask>): ReservationTask {
    const newTask: ReservationTask = {
      id: Math.floor(1000 + Math.random() * 9000),
      user_id: taskData.user_id || 914029411,
      account_id: taskData.account_id || "account_1",
      event_slug: taskData.event_slug || "",
      event_title: taskData.event_title || "",
      category: taskData.category || "Best Available",
      timeslot_id: taskData.timeslot_id || `slot_${Date.now()}`,
      zone: taskData.zone || "Auto-Assigned",
      seat_count: taskData.seat_count || 1,
      status: "RUNNING",
      worker_id: `wrk_sa_riyadh_0${Math.floor(Math.random() * 3) + 1}`,
      retry_count: 0,
      sniper_mode: taskData.sniper_mode ?? true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      logs: [
        {
          timestamp: new Date().toISOString(),
          state: "QUEUED",
          message: `Task initialized for ${taskData.event_title || taskData.event_slug} (${taskData.seat_count} seats)`,
        },
        {
          timestamp: new Date(Date.now() + 200).toISOString(),
          state: "SEARCHING",
          message: `Searching Webook inventory for section: ${taskData.category}`,
        },
      ],
    };

    this.tasks.unshift(newTask);

    // Simulate high-speed auto sniper progression
    setTimeout(() => {
      const target = this.tasks.find((t) => t.id === newTask.id);
      if (target) {
        target.status = "HOLDING";
        target.hold_token = `wbk_hld_${Math.random().toString(36).substring(2, 14)}${Math.random().toString(36).substring(2, 6)}`;
        target.hold_expires_at = new Date(Date.now() + 1000 * 60 * 15).toISOString();
        target.reservation_id = `res_${Math.floor(1000000 + Math.random() * 9000000)}`;
        if (!target.logs) target.logs = [];
        target.logs.push({
          timestamp: new Date().toISOString(),
          state: "HOLDING",
          message: `Successfully claimed seats via Webook SeatCloud. Hold token issued: ${target.hold_token}`,
        });
        target.updated_at = new Date().toISOString();
      }
    }, 1200);

    setTimeout(() => {
      const target = this.tasks.find((t) => t.id === newTask.id);
      if (target && target.status === "HOLDING") {
        target.status = "SUCCESS";
        if (!target.logs) target.logs = [];
        target.logs.push({
          timestamp: new Date().toISOString(),
          state: "SUCCESS",
          message: `Reservation confirmed and locked. Ready for checkout at Webook.com!`,
        });
        target.updated_at = new Date().toISOString();
      }
    }, 3200);

    return newTask;
  }

  public retryTask(taskId: number): ReservationTask | null {
    const task = this.tasks.find((t) => t.id === taskId);
    if (!task) return null;
    task.status = "RUNNING";
    task.retry_count += 1;
    task.error_message = undefined;
    if (!task.logs) task.logs = [];
    task.logs.push({
      timestamp: new Date().toISOString(),
      state: "RUNNING",
      message: `Retrying reservation task (Attempt #${task.retry_count + 1})`,
    });
    task.updated_at = new Date().toISOString();

    setTimeout(() => {
      task.status = "HOLDING";
      task.hold_token = `wbk_hld_${Math.random().toString(36).substring(2, 12)}`;
      task.hold_expires_at = new Date(Date.now() + 1000 * 60 * 15).toISOString();
      if (!task.logs) task.logs = [];
      task.logs.push({
        timestamp: new Date().toISOString(),
        state: "HOLDING",
        message: `Acquired lock on retry. Hold token: ${task.hold_token}`,
      });
      task.updated_at = new Date().toISOString();
    }, 1500);

    return task;
  }

  public syncInventory(): void {
    this.lastSyncTime = new Date().toISOString();
    // Refresh availability counters
    this.events.forEach((ev) => {
      ev.synced_at = this.lastSyncTime;
      ev.sections?.forEach((sec) => {
        const delta = Math.floor(Math.random() * 5) - 2;
        sec.available_seats = Math.max(0, Math.min(sec.total_seats, sec.available_seats + delta));
      });
    });
  }
}

export const dbStore = new DatabaseStore();
