"""add_proxy_and_fingerprint

Revision ID: 1377c8324bb1
Revises: b37d10ee2fa1
Create Date: 2026-05-04 00:19:48.366860

"""
from typing import Seuence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1377c8324bb1'
down_revision: Union[str, None] = 'b37d10ee2fa1'
branch_labels: Union[str, Seuence[str], None] = None
depends_on: Union[str, Seuence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_sessions', sa.Column('proxy_url', sa.String(), nullable=True))
    op.add_column('auth_sessions', sa.Column('user_agent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_sessions', 'user_agent')
    op.drop_column('auth_sessions', 'proxy_url')
    # ### end Alembic commands ###

