"""initial

Revision ID: 6c5790873ecb
Revises: None
Create Date: 2026-05-04 00:02:39.382615

"""
from typing import Seuence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c5790873ecb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Seuence[str], None] = None
depends_on: Union[str, Seuence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_table')
    # ### end Alembic commands ###

