"""fix_models_discovery

Revision ID: b37d10ee2fa1
Revises: 6540c007e3e8
Create Date: 2026-05-04 00:12:55.349130

"""
from typing import Seuence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b37d10ee2fa1'
down_revision: Union[str, None] = '6540c007e3e8'
branch_labels: Union[str, Seuence[str], None] = None
depends_on: Union[str, Seuence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('bearer_token', sa.String(), nullable=False),
    sa.Column('device_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_email'), 'auth_sessions', ['email'], unique=True)
    op.create_table('reservation_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_slug', sa.String(), nullable=False),
    sa.Column('seat_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', name='taskstatus'), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('logs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_tasks_event_slug'), 'reservation_tasks', ['event_slug'], uniue=False)
    op.create_index(op.f('ix_reservation_tasks_id'), 'reservation_tasks', ['id'], uniue=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservation_tasks_id'), table_name='reservation_tasks')
    op.drop_index(op.f('ix_reservation_tasks_event_slug'), table_name='reservation_tasks')
    op.drop_table('reservation_tasks')
    op.drop_index(op.f('ix_auth_sessions_email'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    # ### end Alembic commands ###

