"""add_hold_tracking

Revision ID: d40c8b30be36
Revises: 1377c8324bb1
Create Date: 2026-05-04 00:20:14.910189

"""
from typing import Seuence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd40c8b30be36'
down_revision: Union[str, None] = '1377c8324bb1'
branch_labels: Union[str, Seuence[str], None] = None
depends_on: Union[str, Seuence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation_tasks', sa.Column('hold_token', sa.String(), nullable=True))
    op.add_column('reservation_tasks', sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation_tasks', 'hold_expires_at')
    op.drop_column('reservation_tasks', 'hold_token')
    # ### end Alembic commands ###

